channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python
  - conda-forge::pip=22.3.1
  - conda-forge::python=3.11.0
  - conda-forge::setuptools=65.5.1
  - conda-forge::wheel=0.38.4
  # R
  - conda-forge::r-base=4.2.2
  - conda-forge::r-essentials=4.2
  # Stats Libs
  - bioconda::r-mixomics=6.3.2
  - conda-forge::r-rvaidememoire=0.9_81_2
  - conda-forge::r-xnomial=1.0.4
  # Extras
  - conda-forge::just=1.8.0
  - pip:
    # Book
    - jupyter-book==0.13.1
    - jupyterlab==3.5.0
    # Stats Libs
    - numpy==1.23.4
    - pandas==1.5.1
    - scipy==1.9.3
    - statsmodels==0.13.5