channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python
  - conda-forge::pip
  - conda-forge::python>=3.10
  - conda-forge::setuptools
  - conda-forge::wheel
  # R
  - conda-forge::r-base>=4.2
  - conda-forge::r-essentials
  # Stats Libs
  # - conda-forge::r-mixomics>=6
  - bioconda::bioconductor-mixomics
  - conda-forge::r-rvaidememoire
  - conda-forge::r-xnomial
  - conda-forge::r-ggplot2
  - conda-forge::r-ggthemes
  - conda-forge::r-scales
  - conda-forge::r-nortest
  - conda-forge::r-ez
  - conda-forge::r-fitdistrplus
  - conda-forge::r-coin
  # Extras
  - conda-forge::just
  - pip:
    # Book
    - jupyter-book==0.13.1
    - jupyterlab>=3.5
    # Stats Libs
    - numpy>=1
    - pandas>=1
    - scipy>=1
    - statsmodels>=0.13