channels:
  - conda-forge
dependencies:
  # Python
  - pip>=22.2
  - python>=3.10
  - setuptools>=65
  - wheel>=0.37.1
  # R
  - r-base>=4
  - r-essentials>=3
  # Extras
  - just
  - pip:
    - jupyter-book==0.13.1
    - matplotlib
    - numpy
    - statsmodels
    - jupyterlab
    - scipy