name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

# This job installs dependencies, builds the book, and makes the html available to download
jobs:
  # Build the book!
  build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup Langs and Tools
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Install deps
    - name: Install dependencies
      run: |
        just install

    # Build the book
    - name: Build the book
      run: |
        just build
        touch _build/html/.nojekyll

    # Upload the book's HTML to GH Artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: stats-book-html
        path: _build/html/
        retention-days: 1
    
    # Publish to GH Pages
    - name: Publish Book
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _build/html/